
services:
  # Redpanda (NATS-совместимый брокер)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:29092
    ports:
      - "9092:9092"     # для внутренних сервисов
      - "29092:29092"   # для локального подключения
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  # Redpanda Console 
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8081:8080"    # 8081, чтобы не конфликтовало с приложением
    environment:
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      - redpanda

  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: WB_L0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5037
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d WB_L0"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


  # Сервис миграций 
  migrations:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: migrations
    command: >
      sh -c "
        echo 'Ждём готовности БД...' &&
        sleep 10 &&
        echo 'Загружаем goose...' &&
        wget -O /usr/local/bin/goose https://github.com/pressly/goose/releases/download/v3.25.0/goose_linux_x86_64 &&
        chmod +x /usr/local/bin/goose &&
        echo 'Применяем миграции...' &&
        goose -dir /app/migrations postgres 'host=postgres user=postgres password=5037 dbname=WB_L0 sslmode=disable' up &&
        echo 'Миграции применены!' &&
        exit 0
      "
    depends_on:
      postgres:
        condition: service_healthy  # ждём готовности БД
    restart: on-failure  # перезапуск только при ошибке

  # Go-приложение
  app:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile  
    container_name: wb-app
    ports:
      - "8080:8080"    # Основное приложение
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=WB_L0
      - DB_USER=postgres
      - DB_PASSWORD=5037
      - NATS_URL=redpanda:9092
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy  # Ждем готовности БД
      redpanda:
        condition: service_started
    restart: unless-stopped 

volumes:
  redpanda-data:
  postgres-data: